version: '2.4'
services:
 mariadb:
  image: 'mariadb:10.5.5'
  container_name: 'mariadb'
  restart: 'always'
  environment:
   MYSQL_USER: 'dandelion'
   MYSQL_PASSWORD: 'dandelion123'
   MYSQL_ROOT_PASSWORD: mysql@1234
   TZ: 'Asia/Shanghai'
  ports:
   - '3306:3306'
  volumes:
   - '/data/mariadb/:/var/lib/mysql'
   - '/log/mariadb/:/var/log/mysql'
   - '/data/mysql/init:/docker-entrypoint-initdb.d/'
 emqx:
  container_name: 'emqx'
  image: 'emqx/emqx:4.3.0'
  restart: 'always'
  shm_size: '1G'
  environment:
   EMQX_LOADED_PLUGINS: 'emqx_auth_mnesia'
   TZ: 'Asia/Shanghai'
   EMQX_ALLOW_ANONYMOUS: 'false'
   EMQX_AUTH__USER__1__USERNAME: 'root'
   EMQX_AUTH__USER__1__PASSWORD: abc@1234
   EMQX_AUTH__USER__PASSWORD_HASH: 'sha256'
  ports:
   - '1883:1883'
   - '8081:8081'
   - '15675:8083'
   - '8883:8883'
   - '8084:8084'
   - '18083:18083'
  logging:
   driver: 'json-file'
   options:
    max-size: '100M'
 redis:
  image: 'redis:6.2.4-alpine'
  container_name: 'redis'
  restart: 'always'
  environment:
    TZ: 'Asia/Shanghai'
  command: redis-server --requirepass redis12345
  volumes:
   - '/config/redis/conf/:/usr/redis/'
   - '/data/:/data/'
  ports:
   - '6379:6379'

